---
title: "groton"
author: "greta-anesko"
date: "2026-02-11"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(here)
```

```{r}
com_other <- read_csv(here("Groton", "Commercial  Industial Report.csv"), show_col_types = FALSE)
com_fuel <- read_csv(here("Groton", "Commercial Fuel Type.csv"), show_col_types = FALSE)
condo_other <- read_csv(here("Groton", "Condo Report.csv"), show_col_types = FALSE)
condo_fuel <- read_csv(here("Groton", "Condo Fuel Type.csv"), show_col_types = FALSE)
res_other <- read_csv(here("Groton", "Report Residential.csv"), show_col_types = FALSE)
res_fuel <- read_csv(here("Groton", "Residential Fuel Type.csv"), show_col_types = FALSE)
```

```{r}
com_other_filter <- com_other %>%
  select(Location, Primary_Use, Stories, Living_AreaGBA) %>%
  rename(USECODE = Primary_Use, STORYHEIGHT = Stories, AREASQ = Living_AreaGBA) %>%
  group_by(Location) %>%
  mutate(cumsum = row_number()) %>%
  ungroup() %>%
  unite("Location", Location, cumsum, sep = "_")

com_fuel_filter <- com_fuel %>%
  select(Location, Usrfld_207_Desc) %>%
  rename(FUELTYPE = Usrfld_207_Desc) %>%
  group_by(Location) %>%
  mutate(cumsum = row_number()) %>%
  ungroup() %>%
  unite("Location", Location, cumsum, sep = "_")

condo_other_filter <- condo_other %>%
  select(Location, Primary_Use, Stories, Living_AreaGBA) %>%
  rename(USECODE = Primary_Use, STORYHEIGHT = Stories, AREASQ = Living_AreaGBA) %>%
  group_by(Location) %>%
  mutate(cumsum = row_number()) %>%
  ungroup() %>%
  unite("Location", Location, cumsum, sep = "_")

condo_fuel_filter <- condo_fuel %>%
  select(Location, Heat_Sys_Desc) %>%
  rename(FUELTYPE = Heat_Sys_Desc) %>%
  group_by(Location) %>%
  mutate(cumsum = row_number()) %>%
  ungroup() %>%
  unite("Location", Location, cumsum, sep = "_")

res_other_filter <- res_other %>%
  select(Location, Primary_Use, Stories, Living_AreaGBA) %>%
  rename(USECODE = Primary_Use, STORYHEIGHT = Stories, AREASQ = Living_AreaGBA) %>%
  group_by(Location) %>%
  mutate(cumsum = row_number()) %>%
  ungroup() %>%
  unite("Location", Location, cumsum, sep = "_")

res_fuel_filter <- res_fuel %>%
  select(Location, Usrfld_82_Desc) %>%
  rename(FUELTYPE = Usrfld_82_Desc) %>%
  group_by(Location) %>%
  mutate(cumsum = row_number()) %>%
  ungroup() %>%
  unite("Location", Location, cumsum, sep = "_")
  
```

```{r}
com_merge <- inner_join(com_other_filter, com_fuel_filter, by = "Location")
condo_merge <- inner_join(condo_other_filter, condo_fuel_filter, by = "Location")
res_merge <- inner_join(res_other_filter, res_fuel_filter, by = "Location")
```

```{r}
# if four digits: remove last digit
# else: nothing

com <- com_merge %>%
  mutate(USECODE = substr(USECODE, 1, 3)) %>%
  select(USECODE, FUELTYPE, AREASQ, STORYHEIGHT)

condo <- condo_merge %>%
  mutate(USECODE = substr(USECODE, 1, 3)) %>%
  select(USECODE, FUELTYPE, AREASQ, STORYHEIGHT)

res <- res_merge %>%
  mutate(USECODE = substr(USECODE, 1, 3)) %>%
  select(USECODE, FUELTYPE, AREASQ, STORYHEIGHT)
```

```{r}
df <- bind_rows(com, condo, res)
```

```{r}
write.csv(df, file = "Groton_Final.csv", row.names = FALSE)
```

